[View in Colaboratory](https://colab.research.google.com/github/sabumjung/DL-with-TensorFlow/blob/DL-with-TensorFlow/10%EC%9E%A5_1.ipynb)

In [1]:
!pip install gym

    100% |████████████████████████████████| 1.5MB 9.6MB/s 
    100% |████████████████████████████████| 1.0MB 11.3MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /content/.cache/pip/wheels/cb/14/71/f4ab006b1e6ff75c2b54985c2f98d0644fffe9c1dddc670925
Successfully built gym


In [0]:
import gym
import numpy as np

In [0]:
env = gym.make('FrozenLake-v0')

In [4]:
# 강화학습 대상 테이블 초기화(0으로 설정)
Q = np.zeros([env.observation_space.n,env.action_space.n])

# 학습 파라미터 설정(학습률, 감마, 에피소드 개수)
# 감마 : discount factor으로 상태가치를 계산하는데 있어 미래의 보상을 얼마나 가치있게 고려할지 설정하는 값
# V(s)=E(R_t+1+gamma*R_t+2+gamma^2*R_t+3+ ...|S_t=s)
# 감마값은 0~1의 값을 부여함, 0(t+1만을 보상), 1(t+1을 포함한 전체 미래의 보상을 동일하게 보상)
lr = .85
# 감마값을 0.99로 설정함(t+1의 보상은 그대로, t+2의 보상은 0.99를 곱한 결과를 합산하여 계산함 )
gamma = .99
num_episodes = 2000

# 에피소드별로 총 보상(rewards)와 단계(steps) 정보를 갖는 리스트를 만든다.
rList = []

# 2000 에피소드를 수행한다.
for i in range(num_episodes):

# 매 에피소드마다 환경을 재설정(reset)하고 첫번째 신규 관측값을 가져온다.
    s = env.reset()
    rAll = 0
    d = False
    j = 0

   # Q-Table 학습 알고리즘
    while j < 99:
        j+=1

  # Q-Table에서 탐욕적으로 한가지 행동을 선택한다.
        a = np.argmax(Q[s,:]+ \
                  np.random.randn(1, env.action_space.n)*(1./(i+1)))

  # 환경으로부터 신규 상태와 보상을 가져옮
  # 예) t에서 s(t)일때 a(t)실행시, t+1의 s(t+1)와 r(t+1)을 가져옮
        s1,r,d,_ = env.step(a)

        # 새로운 학습지식을 이용하여 Q-Table을 업데이트한다.
        Q[s,a] = Q[s,a] + lr*(r + gamma *np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break

    rList.append(rAll)

print("Score over time: " +  str(sum(rList)/num_episodes))
print("Final Q-Table Values")
print(Q)

Score over time: 0.6405
Final Q-Table Values
[[3.46337387e-03 3.96877616e-03 5.17902900e-01 2.53784196e-03]
 [3.17708951e-04 6.14926482e-04 3.23661992e-05 1.55125597e-01]
 [1.44661164e-03 4.31767370e-02 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.33889650e-01]
 [7.86296905e-01 1.93440942e-03 3.91992573e-04 5.60227354e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.08376869e-03 4.19097965e-04 1.00737986e-04 2.40367890e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.81370572e-05 6.61304472e-04 2.56416710e-04 7.55875215e-01]
 [1.13995211e-03 3.06683242e-01 0.00000000e+00 0.00000000e+00]
 [8.49182801e-01 4.05431102e-04 3.20683231e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.13962982e-02 0.00000000e+00 8.96442088e-01 0.00000000e+00]
 [0.00000000e+00 9.95228162e-01 0.00000000e+00 0.00000000e+00]
 [0.000000